# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Calculator' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  # Pods for Calculator

  target 'CalculatorTests' do
    inherit! :search_paths
    use_frameworks!

    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
    
  end
end
